### PR TITLE
Reorganized project and made it more user-friendly

### PR DESCRIPTION
**Pull request by Zrp200**
- I don't know how to read the signs while running the game
- `prompt_user` not colorizing

### CODE REVIEW

**Comment by Zrp200** [comment]
Don't worry, I tested it already

**Comment by Zrp200** [comment]
By the way, you should make it obvious what the exits are _in_ the paragraphs, not below them

**Comment by Zrp200** [comment]
I can't do much with `world.rb`; I don't know exactly what it does

**Comment by Zrp200** [comment]
@andy-j :worried: :sos:  Please don't give up on this project. I'm working on battles right now. Next on my list is creating a way to save the game. However, I need you since I don't have a clue how to work the world file. I really think this can go places.

**Comment by andy-j** [comment]
Hey Zachary!

I really appreciate the time you're putting in to improving this! This project is a way for me to figure out how things work in ruby, as well as a bit of a throwback to CircleMUD games I played in the past. I won't be able to merge these changes in (though I did end up replicating a few of them as things got moved around), but feel free to keep playing around! I'm going to put together a 'monster' class and implement a fight system that I have drawn out here. Once I am finished with that, I would love to share my ideas for this with you so you know where I'm going.

Again, feel free to keep working on it - I look forward to seeing what you come up with!

Thanks,

Andy

**Comment by Zrp200** [comment]
I already made a monster class as `Creature`

**Pull request closed without merging**
